language: generic
# Tell Travis we need docker
services:
 - docker
# Tell Travis how to deploy code to AWS
deploy:
 -  provider: elasticbeanstalk # We will deploy code to Elastic Beanstalk
    region: ap-south-1 # Specify your region
    app: "my-first-app" # Copy it from Elastic Beanstalk dashboard
    env: "Myfirstapp-env" # Copy it from Elastic Beanstalk dashboard
    # Access Key ID and Secret Access Key as configured in IAM of AWS.
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    # Elastic Beanstalk will take code from S3 bucket and deploy it in container.
    # Take it from AWS S3
    bucket_name: "my-first-app-bucket"
    # Folder where Travis CI will upload the code in zip file in this folder. Take it from AWS S3
    bucket_path: "docker"
    on:
    # Deploy only when there are changes on master branch
        branch: main

-   provider: elasticbeanstalk # We will deploy code to Elastic Beanstalk
    region: ap-south-1 # Specify your region
    app: "my-first-app" # Copy it from Elastic Beanstalk dashboard
    env: "Myfirstapp-env" # Copy it from Elastic Beanstalk dashboard
    # Access Key ID and Secret Access Key as configured in IAM of AWS.
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    # Elastic Beanstalk will take code from S3 bucket and deploy it in container.
    # Take it from AWS S3
    bucket_name: "my-first-app-bucket"
    # Folder where Travis CI will upload the code in zip file in this folder. Take it from AWS S3
    bucket_path: "docker"
    on:
    # Deploy only when there are changes on master branch
        branch: testing
